services:
  cognee:
    container_name: cognee
    networks:
      - cognee-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/cognee-frontend/ # Ignore frontend code
    environment:
      - HOST=0.0.0.0
      - ENVIRONMENT=local
      - PYTHONPATH=.
    ports:
      - 8000:8000
      # - 5678:5678 # Debugging
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 8GB

  frontend:
    container_name: frontend
    build:
      context: ./cognee-frontend
      dockerfile: Dockerfile
    volumes:
      - ./cognee-frontend/src:/app/src
      - ./cognee-frontend/public:/app/public
    ports:
      - 3000:3000
      # - 9229:9229 # Debugging
    networks:
      - cognee-network

networks:
  cognee-network:
    name: cognee-network
